# -*- coding: utf-8 -*-
"""Spectral Alignment in QML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T4JJGTm-xMspkTZeMOKudUZYDlkOPBjg
"""

!pip install yfinance

import yfinance as yf
import pandas as pd

tickers = ["AAPL", "AMZN", "GOOGL", "META", "NFLX"]

data = yf.download(tickers, start="2015-01-01", end="2024-12-31")
data.head()

!pip install yfinance ta

import yfinance as yf
import pandas as pd
import numpy as np

# FAANG tickers (META instead of FB)
tickers = ["AAPL", "AMZN", "GOOGL", "META", "NFLX"]

data = yf.download(tickers, start="2015-01-01", end="2024-12-31", group_by='ticker')

data.head()

dfs = []

for ticker in tickers:
    df = data[ticker].copy()
    df["Ticker"] = ticker
    df.reset_index(inplace=True)
    dfs.append(df)

df = pd.concat(dfs)
df.head()

import ta

def add_indicators(df):
    df["RSI"] = ta.momentum.RSIIndicator(df["Close"]).rsi()
    df["SMA_20"] = ta.trend.SMAIndicator(df["Close"], window=20).sma_indicator()
    df["EMA_20"] = ta.trend.EMAIndicator(df["Close"], window=20).ema_indicator()

    macd = ta.trend.MACD(df["Close"])
    df["MACD"] = macd.macd()
    df["MACD_signal"] = macd.macd_signal()

    bb = ta.volatility.BollingerBands(df["Close"])
    df["BB_high"] = bb.bollinger_hband()
    df["BB_low"] = bb.bollinger_lband()

    return df

df = df.groupby("Ticker").apply(add_indicators).reset_index(drop=True)

df.head()

import ta

def add_indicators(df):
    df["RSI"] = ta.momentum.RSIIndicator(df["Close"]).rsi()
    df["SMA_20"] = ta.trend.SMAIndicator(df["Close"], window=20).sma_indicator()
    df["EMA_20"] = ta.trend.EMAIndicator(df["Close"], window=20).ema_indicator()

    macd = ta.trend.MACD(df["Close"])
    df["MACD"] = macd.macd()
    df["MACD_signal"] = macd.macd_signal()

    bb = ta.volatility.BollingerBands(df["Close"])
    df["BB_high"] = bb.bollinger_hband()
    df["BB_low"] = bb.bollinger_lband()

    return df

df = df.groupby("Ticker").apply(add_indicators).reset_index(drop=True)

df.head()

df["Future_Close"] = df.groupby("Ticker")["Close"].shift(-1)
df["Target"] = (df["Future_Close"] > df["Close"]).astype(int)

df = df.dropna()

df[["Close", "Future_Close", "Target"]].head()

from sklearn.model_selection import train_test_split

features = [
    "RSI", "SMA_20", "EMA_20",
    "MACD", "MACD_signal",
    "BB_high", "BB_low", "Volume"
]

X = df[features]
y = df["Target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds))

from sklearn.model_selection import train_test_split

features = [
    "RSI", "SMA_20", "EMA_20",
    "MACD", "MACD_signal",
    "BB_high", "BB_low", "Volume"
]

X = df[features]
y = df["Target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds))

import matplotlib.pyplot as plt

importance = pd.Series(model.feature_importances_, index=features)
importance.sort_values().plot(kind="barh", figsize=(8,6))
plt.title("Feature Importance")
plt.show()

df_test = df.iloc[-len(y_test):].copy()
df_test["Prediction"] = preds

# Strategy Return
df_test["Market_Return"] = df_test["Close"].pct_change()
df_test["Strategy_Return"] = df_test["Market_Return"] * df_test["Prediction"]

df_test.head()

df_test["Cumulative_Market"] = (1 + df_test["Market_Return"]).cumprod()
df_test["Cumulative_Strategy"] = (1 + df_test["Strategy_Return"]).cumprod()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
plt.plot(df_test["Cumulative_Market"], label="Buy & Hold")
plt.plot(df_test["Cumulative_Strategy"], label="Model Strategy")
plt.legend()
plt.title("Strategy vs Market Performance")
plt.show()

# Sharpe Ratio
sharpe = df_test["Strategy_Return"].mean() / df_test["Strategy_Return"].std()
print("Sharpe Ratio:", sharpe)

# Max Drawdown
cum_returns = df_test["Cumulative_Strategy"]
rolling_max = cum_returns.cummax()
drawdown = cum_returns / rolling_max - 1
max_drawdown = drawdown.min()

print("Max Drawdown:", max_drawdown)

from sklearn.preprocessing import StandardScaler
import numpy as np

# Use the same feature list
features = [
    "RSI", "SMA_20", "EMA_20",
    "MACD", "MACD_signal",
    "BB_high", "BB_low", "Volume"
]

X_features = df[features].dropna()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_features)

X_scaled.shape

# Covariance matrix
cov_matrix = np.cov(X_scaled, rowvar=False)

cov_matrix.shape

eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)

# Sort descending
idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

eigenvalues

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(eigenvalues, marker='o')
plt.title("Eigenvalue Spectrum of Technical Indicators")
plt.xlabel("Component Index")
plt.ylabel("Eigenvalue")
plt.show()

plt.figure(figsize=(8,5))
plt.loglog(range(1, len(eigenvalues)+1), eigenvalues, marker='o')
plt.title("Log-Log Eigenvalue Spectrum")
plt.xlabel("Component Index (log)")
plt.ylabel("Eigenvalue (log)")
plt.show()

explained_variance_ratio = eigenvalues / eigenvalues.sum()

plt.figure(figsize=(8,5))
plt.bar(range(len(explained_variance_ratio)), explained_variance_ratio)
plt.title("Explained Variance Ratio")
plt.show()

cumulative_variance = np.cumsum(explained_variance_ratio)

intrinsic_dim_95 = np.argmax(cumulative_variance >= 0.95) + 1

print("Intrinsic Dimension (95% variance):", intrinsic_dim_95)

!git clone https://github.com/shankar27git/Spectral-Alignment-in-QML.git

!git config --global user.name "shankar27git"
!git config --global user.email "shankar.narayanan@zensar.com"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!git clone https://github.com/shankar27git/Spectral-Alignment-in-QML.git

# Commented out IPython magic to ensure Python compatibility.
# %cd Spectral-Alignment-in-QML

!git config --global user.name "shankar27git"
!git config --global user.email "shankar.narayanan@zensar.com"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/shankar27git/Spectral-Alignment-in-QML.git
# %cd Spectral-Alignment-in-QML

from google.colab import _message
import json, pathlib

nb = _message.blocking_request("get_ipynb", request={})
pathlib.Path("Spectral Alignment in QML.ipynb").write_text(json.dumps(nb["ipynb"]))